### PR TITLE
single key strafing

### PR DESCRIPTION
**Pull request by ohmailon**
# Still in Progress & adding some more Features

In Keys2XInput we got the ability to set the options in a way that allows us to strafe while only pressing A or D without the need of pressing W. This should be the same feature but in the wooting style with a fancy slider & a simple option to disable it :)

image

### CODE REVIEW

**Comment by PastaJ36** [comment]
Hey, thanks for the PR! We're in the middle of a keyboard launch, so we won't have time to review it fully this week. From a first look it looks very good, thanks again.

**Comment by PastaJ36** [comment]
Can you split the binds per direction and strafing option in separate PR's? I can imagine we will have different requirements for these features. Want to prevent one being dependant on the other

**Comment by ohmailon** [comment]
I created a new PR for the multiple binds thing https://github.com/WootingKb/wooting-double-movement/pull/17
For the strafing slider part: I'm gonna keep it in this branch since this branch implements already the feature with the multiple binds. If we don't merge the other PR for some reason, i can still make another PR to merge it into your fix/ds4 branch branch.

**Comment by ohmailon** [comment]
I'll close this draft because i've made a new/simpler implementation of it, since i know the application now a bit better and how its built :)

**Pull request closed without merging**
